### ISSUE TITLE
git deps cause grief for some

### ISSUE THREAD

**Issue by stefanpenner** [airportyh/testem#660] opened 2015-11-10 17:12 UTC
For some users (often those with strict corp policies) GIT dependencies cause grief

https://github.com/airportyh/testem/blob/master/package.json#L42

```
└─┬ testem@0.9.9
  └─┬ socket.io@1.3.7 (git://github.com/patocallaghan/socket.io.git#c1182cae6038a2b65eb13779052b0c3793a04938)
    └─┬ engine.io@1.5.4 (git://github.com/patocallaghan/engine.io.git#22b6418a55671a085c4ac87708eae24c14228934)
      └── ws@0.8.0  (git://github.com/patocallaghan/ws.git#892ea5f4dfc1cd4cb18d36cce446bef0d8039cf
```

those variants will need to be published to `npm`, let me propose the `-pure` suffix.

* `socket.io-pure`
* `engine.io-pure`
* `ws-pure`

cc @patocallaghan

**Comment by stefanpenner** [comment] 2015-11-10 17:22
@johanneswuerbach ideally I would love a release with ^ asap. Let me know your schedule, so I can be sure this is fixed quick enough that your schedule still allows a release.

**Comment by johanneswuerbach** [comment] 2015-11-10 17:26
Duplicate of https://github.com/airportyh/testem/issues/659 . I don't have access to push those forks to npm :-( After they are pushed, I can cut a new release until 23 CET.

**Comment by patocallaghan** [comment] 2015-11-10 17:26
Yep , will try get these out ASAP

**Comment by patocallaghan** [comment] 2015-11-10 17:49
https://www.npmjs.com/package/ws-pure
https://www.npmjs.com/package/engine.io-pure
https://www.npmjs.com/package/socket.io-pure
https://www.npmjs.com/package/socket.io-client-pure

Here's the packages published to npm although each repo will need to be updated to point to one another.

@johanneswuerbach I'll give you access also, just in case you ever need it

**Comment by johanneswuerbach** [comment] 2015-11-10 18:36
Will merge and release https://github.com/airportyh/testem/pull/661 as soon as everything passed, we still need to link all packages to each other. I could do that, but I would need access to your forks @patocallaghan

**Comment by johanneswuerbach** [comment] 2015-11-10 22:13
@patocallaghan mind also adding me to your `engine.io-client-pure` Apparently this also needs a few changes to use the `ws-pure` version

**Closed** 2015-11-10 22:39 UTC
